# Site settings
title: "飞碟说"
author: "JetChan"
description: "一个独立博客"
keywords: "数据分析, 可视化, 图表, 报表, 大数据, 数据挖掘, 哲学, 金融, 经济, R语言, Python, 分析工具, excel, 数据库, Mysql"
biography: "白日梦想家"
colophon: "© MMXIII — MMXVI by JetChan.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://wwww.chenhuijie.com"


weibo_username: chenhuijie23
github_username: chenhuijie23
google-analytics: UA-90696094-1

simple_search: http://baidu.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
